variables:
  - name: BuildParameters.solution
    value: '**\*.sln'
  - name: BuildParameters.ArtifactName
    value: omnikassa-dotnet-sdk
trigger:
  branches:
    include:
      - master
      - feature/*
schedules:
  - cron: 0 22 * * 0
    branches:
      include:
        - develop
    always: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: master
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      name: Rabo-Windows-Production
    steps:
      - checkout: self
        persistCredentials: True
      - task: CredScan@2
        displayName: Run Credential Scanner
      - task: NuGetToolInstaller@0
        displayName: Use NuGet 4.4.1
        inputs:
          versionSpec: 4.4.1
      - task: NuGetCommand@2
        displayName: NuGet restore
        inputs:
          solution: $(BuildParameters.solution)
      - task: SonarQubePrepare@4
        displayName: Prepare analysis on SonarQube
        inputs:
          SonarQube: 1d70f66a-3a69-4f69-92bd-c4499862de0b
          projectKey: nl.rabobank.gict.payments_savings.omnikassa_frontend.sdk:dotnet
          projectName: Rabobank OmniKassa - .NET SDK
          extraProperties: sonar.exclusions=samples/**
      - task: VSBuild@1
        displayName: Build Omnikassa SDK
        inputs:
          solution: OmniKassa.sln
          msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
      - task: VSTest@2
        displayName: Test Assemblies
        inputs:
          testAssemblyVer2: >-
            **\$(BuildConfiguration)\**\*test*.dll

            !**\obj\**
          codeCoverageEnabled: true
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
      - task: SonarQubeAnalyze@4
        displayName: Run Code Analysis
      - task: SonarQubePublish@4
        displayName: Publish Quality Gate Result
      - task: CmdLine@2
        displayName: Set Java to Version 11
        inputs:
          script: >-
            echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"

            echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
      - task: NexusIqPipelineTask@1
        displayName: Nexus IQ policy evaluation
        inputs:
          nexusIqService: 69af253f-faf5-4412-95ae-d4cd5300eac6
          applicationId: omnikassa-frontend-sdk-net
          stage: Develop
          scanTargets: src/**/*.dll
      - task: VSBuild@1
        displayName: Build Omnikassa SDK Samples
        inputs:
          solution: OmniKassa.Samples.sln
          msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
          platform: $(BuildPlatform)
          configuration: $(BuildConfiguration)
      - task: PostAnalysis@1
        displayName: Post Analysis
        inputs:
          CredScan: true
      - task: PublishSymbols@2
        displayName: Publish symbols path
        continueOnError: True
        inputs:
          SearchPattern: '**\bin\**\*.pdb'
          PublishSymbols: false
          SymbolServerType: TeamServices
      - task: PublishBuildArtifacts@1
        displayName: Publish Artifact
        condition: succeededOrFailed()
        inputs:
          PathtoPublish: $(build.artifactstagingdirectory)
          ArtifactName: $(BuildParameters.ArtifactName)
          TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
  - job: "security_gate"
    displayName: "Security gate"
    pool:
      name: Rabo-Linux-Production
    steps:
      - checkout: self
        persistCredentials: True
      - task: FortifySCA@5
        displayName: Run Fortify
        inputs:
          applicationType: other
          fortifyProjects: OmniKassa.sln
          buildToolOptions: -dotnet-version 2.1
          fortifyBuildId: rofe
          runFortifyUpload: true
          fortifyServerName: a19e78a6-1cac-43ef-8dec-6e30e9136511
          fortifyApplicationName: ps_omnikassa-dotnet-sdk_fortify
          fortifyApplicationVersion: 1.0